services:
  - type: web
    name: dich-thuat
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production

